//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string UnitOfMeaserent { get; set; }
        public decimal Price { get; set; }
        public int Discount { get; set; }
        public int CountInStorage { get; set; }
        public string Description { get; set; }
        public int GoodCategoryId { get; set; }
        public int SupplierId { get; set; }
        public int ManufactureId { get; set; }
        public string PicturePass { get; set; }
    
        public virtual GoodCategory GoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
